package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "record_store",
    srcs = ["record_store.cc"],
    hdrs = ["record_store.h"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
)